namespace Wypozyczalnia
{
    enum Commands
    {
       NULL, POMOC, ZALOGUJ, ZAREJESTRUJ, WYLOGUJ, DODAJPOJAZD, POKAZPOJAZDY,
       POKAZKONTA, DODAJADMINA, ZMIENSTATUS, USUNPOJAZD, WYPOZYCZ, ZWROC, ZAREZERWUJ,
       WIADOMOSC
    }
}
